main/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.login_user, name='home'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^crl/$', views.clientRequestList, name='clientRequestList'),
    url(r'^carl/$', views.commonAreaRequestList, name='commonAreaRequestList'),
    url(r'^user/$', views.userInfo, name="userInfo"),
    url(r'^t/$', views.technicianList, name="technicianList"),
    #/music/<album_id>/
    url(r'^crl/(?P<pk>[0-9]+)/$', views.clientRequestDetail.as_view(), name='clientRequestDetail'),
    url(r'^carl/(?P<pk>[0-9]+)/$', views.commonAreaRequestDetail.as_view(), name='commonAreaRequestDetail'),
]
admin.site.site_header = 'Work Order System Admin Area'
admin.site.site_title = 'Work Order System Admin Area'

workOrderSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

LOCATION_CHOICES = (
    ("B1","Building 1"),
    ("B2","Building 2"),
    ("B3","Building 3"),
    ("B4","Building 4"),
)

class Client(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    location = models.CharField(max_length=100,choices=LOCATION_CHOICES)
    room_number = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    
    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

class CommonArea(models.Model):
    area_name = models.CharField(max_length=100)
    location = models.CharField(max_length=100,choices=LOCATION_CHOICES)
    
    def __str__(self):
        return "{}".format(self.area_name)

class ClientRequest(models.Model):
    title = models.CharField(max_length=100)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    description = models.TextField(max_length=10000)
    due_date = models.DateField()
    technician = models.ForeignKey(User, on_delete=models.CASCADE)

class CommonAreaRequest(models.Model):
    title = models.CharField(max_length=100)
    common_area = models.ForeignKey(CommonArea, on_delete=models.CASCADE)
    description = models.TextField(max_length=10000)
    due_date = models.DateField()
    technician = models.ForeignKey(User, on_delete=models.CASCADE)

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.defaults import page_not_found
from .models import *
from bs4 import BeautifulSoup
import requests
import json
import urllib
import ast
from Crypto.Cipher import AES
import binascii
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.views import generic

def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        # passphrase = request.POST.get('passphrase')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                # return render(request, 'main/home.html')
                return redirect("main:home")
        else:
            return render(request, 'main/login.html', {'error_message': 'Invalid login'})
    else:
        if request.user.is_authenticated is True:
            return render(request, 'main/home.html')
        elif request.GET.get('next'):
            return render(request, 'main/login.html', {'error_message': 'You must log in to see this page' })
    return render(request, 'main/login.html')
    
def logout_user(request):
    logout(request)
    # return render(request, 'main/home.html')
    return redirect("main:home")

def home(request):
    return render(request, 'main/home.html')

def userInfo(request):
    return render(request, 'main/userInfo.html')

def technicianList(request):
    
    technicianArray = []
    for user in User.objects.filter(groups__name="Technicians"):
        technicianArray += [UserProfile.objects.get(user_account=user)]
    
    x={}
    # x['technicianList'] = User.objects.filter(groups__name="Technicians").order_by('last_name')
    x['technicianList'] = technicianArray
    return render(request, 'main/technicianList.html', x)
    

    
    
    
def clientRequestList(request):
    
    x={}
    x['clientRequestList'] = ClientRequest.objects.all().order_by('due_date')
    
    return render(request, 'main/clientRequestList.html', x)

def commonAreaRequestList(request):
    
    x={}
    x['commonAreaRequestList'] = CommonAreaRequest.objects.all().order_by('due_date')
    
    return render(request, 'main/commonAreaRequestList.html', x)
    
class clientRequestDetail(generic.DetailView):
    model = ClientRequest
    template_name = 'main/clientRequestDetail.html'
    
class commonAreaRequestDetail(generic.DetailView):
    model = CommonAreaRequest
    template_name = 'main/commonAreaRequestDetail.html'
    

# Create your views here.

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    
    <!--allow subtemplates to set page title-->
    <title>{% block title %}{% endblock %}</title>
    
    {% load staticfiles %}
    
    <!--set website icon-->
    <!--<link rel="icon" type="image/png" href="{% static 'cryptocurrency/img/favicon.ico' %}"/>-->
    <link rel="icon" type="image/png" href="https://png.icons8.com/office/16/000000/home.png"/>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta name="viewport" content = "width=device-width, initial-scale=1.0">
    
    <style type="text/css">
      @keyframes example {
          0%   {background-color: #5b8e98;}
          50%  {background-color: #a47167;}
          100% {background-color: #5b8e98;}
      }
      
      body{
          background-color: #030911;
          color:white;
      }
      
      #mainJumbotron{
          /*background-color: royalblue;*/
      }
    </style>
  </head>
  <body>
    <br>
    <div class="container-fluid">
      <div class="row">
      {% if request.user.username %}
        <div class="col-sm-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'main:home' %}">Work Order System</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:clientRequestList' %}">Client Requests</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:commonAreaRequestList' %}">Common Area Requests</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:technicianList' %}">Technicians</a>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              {% if request.user.is_superuser %}
              <li>
                <a id="techFont4" class="nav-item nav-link active" href="{% url 'admin:index' %}">
                  <button type="button" class="btn btn-success btn-sm">Admin Area</button>
                </a>
    	        </li>
    	        {% endif %}
    	        <li>
                <a id="techFont4" class="nav-item nav-link active" href="{% url 'main:logout' %}">
                  <button type="button" class="btn btn-danger btn-sm">Logout</button>
                </a>
    	        </li>
        		</ul>
          </div>
        </nav>
          <br>
        </div>
      {% endif %}

  		{% block body %}
      {% endblock %}
      </div>
    </div>
  </body>
</html>

main/templates/main/clientRequestDetail.html
{% extends 'main/base.html' %}
{% block title %}User Info{% endblock %}

{% block body %}
{% load staticfiles %}
<div class="container-fluid" style="text-align: center;">
  <div class="row">
    <div class="col-sm-12">
      <a href="{% url 'main:clientRequestList' %}"><button type="button" class="btn btn-danger btn-lg btn-block">Back</button></a>
      <br>
      <ul class="list-group" style="color:black;">
        <li class="list-group-item active" style="font-weight: bold;font-size: 150%;">
          #{{ clientrequest.id }}
          <br>
          Title: {{ clientrequest.title }}
        </li>
        <li class="list-group-item">Client: {{ clientrequest.client }}</li>
        <li class="list-group-item">Description:<br>{{ clientrequest.description }}</li>
        <li class="list-group-item">Due Date: {{ clientrequest.due_date }}</li>
        <li class="list-group-item">Technician: {{ clientrequest.technician }}</li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/clientRequestList.html
{% extends 'main/base.html' %}
{% block title %}Request List{% endblock %}

{% block body %}
{% load staticfiles %}
<div class="container-fluid" style="text-align: center;">
    <div class="row">
      <div class="col-sm-12">
        <a href="{% url 'main:home' %}"><button type="button" class="btn btn-danger btn-lg btn-block">Back</button></a>
        <br>
        <h1>Client Request List</h1>
        <br>
        <table class="table table-striped table-light" style="color:black;">
          <thead>
            <tr>
              <th scope="col">Title</th>
              <th scope="col">Due Date</th>
              <th scope="col">Technician</th>
            </tr>
          </thead>
          <tbody>
          {% for r in clientRequestList %}
            <tr>
              <td scope="row"><a href="{% url 'main:clientRequestList' %}{{r.id}}/">{{r.title}}</a></td>
              <td>{{r.due_date}}</td>
              <td>{{r.technician}}<br>{{r.technician.get_full_name}}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
        
          <h1></h1>
          <h1></h1>
          <h1></h1>
        
      </div>
    </div>
</div>
{% endblock %}

main/templates/main/commonAreaRequestDetail.html
{% extends 'main/base.html' %}
{% block title %}User Info{% endblock %}

{% block body %}
{% load staticfiles %}
<div class="container-fluid" style="text-align: center;">
  <div class="row">
    <div class="col-sm-12">
      <a href="{% url 'main:commonAreaRequestList' %}"><button type="button" class="btn btn-danger btn-lg btn-block">Back</button></a>
      <br>
      <ul class="list-group" style="color:black;">
        <li class="list-group-item active" style="font-weight: bold;font-size: 150%;">
          #{{ commonarearequest.id }}
          <br>
          Title: {{ commonarearequest.title }}
        </li>
        <li class="list-group-item">Client: {{ commonarearequest.common_area }}</li>
        <li class="list-group-item">Description:<br>{{ commonarearequest.description }}</li>
        <li class="list-group-item">Due Date: {{ commonarearequest.due_date }}</li>
        <li class="list-group-item">Technician: {{ commonarearequest.technician }}</li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/commonAreaRequestList.html
{% extends 'main/base.html' %}
{% block title %}Request List{% endblock %}

{% block body %}
{% load staticfiles %}
<div class="container-fluid" style="text-align: center;">
    <div class="row">
      <div class="col-sm-12">
        <a href="{% url 'main:home' %}"><button type="button" class="btn btn-danger btn-lg btn-block">Back</button></a>
        <br>
        <h1>Common Area Request List</h1>
        <br>
        <table class="table table-striped table-light" style="color:black;">
          <thead>
            <tr>
              <th scope="col">Title</th>
              <th scope="col">Due Date</th>
              <th scope="col">Technician</th>
            </tr>
          </thead>
          <tbody>
          {% for r in commonAreaRequestList %}
            <tr>
              <td scope="row"><a href="{% url 'main:commonAreaRequestList' %}{{r.id}}/">{{r.title}}</a></td>
              <td>{{r.due_date}}</td>
              <td>{{r.technician}}<br>{{r.technician.get_full_name}}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
        
          <h1></h1>
          <h1></h1>
          <h1></h1>
        
      </div>
    </div>
</div>
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %}Home{% endblock %}

{% block body %}
{% load staticfiles %}
<div class="container-fluid" style="text-align: center;">
    <div class="row">
      <div class="col-sm-12">
        <h1>Work Order System</h1>
        <h2><a href="/crl">Client Requests</a></h2>
        <h2><a href="/carl">Common Area Requests</a></h2>
        <h2><a href="/t">Technicians</a></h2>
      </div>
    </div>
</div>
{% endblock %}

main/templates/main/login.html
{% extends 'main/base.html' %}
{% block title %}Login{% endblock %}

{% block body %}
{% load staticfiles %}

<div class="col-sm-12">
  <img style="max-width:75%;max-height:75%;" src="{% static 'main/company_logo.png' %}">
</div>

<div class="col-sm-12" style="text-align:center;">
  <br>
  <h1>Welcome to the Work Order System!</h1>
  <br>
</div>

<div class="col-sm-6" style="text-align:center;">
  <img style="max-width:100%;max-height:100%;" src="{% static 'main/login_page_picture.png' %}" alt='image goes here'>
</div>

<div class="col-sm-6" style="border: 2px solid white;word-wrap: break-word;border-radius: 15px;text-align:center;margin: 0px auto;">
  <br>
{% if error_message %}
  <h3 style="color:#8e2020;font-weight:bold;">{{ error_message }}</h3>
{% else %}
  <br><br>
{% endif %}
  
  <form role="form" action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
{% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
{% endif %}
    <div class="form-group">
      <label for="id_username">Username:</label>
      <input type="text" class="form-control" name="username" placeholder="Username">
    </div>
    
    <div class="form-group">
      <label for="id_password">Password:</label>
      <input type="password" class="form-control" name="password" placeholder="Password">
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  <br>
</div>

<!--<div class="col-sm-12" style="border: 2px solid white;word-wrap: break-word;border-radius: 0px 0px 15px 15px;background-color:#202020">-->
<!--  <h1 style="font-size: 400%;text-align: center;">Login</h1>-->
<!--</div>-->

<!--<div class="col-sm-12">-->
<!--  <br>-->
<!--</div>-->

<!--<div class="col-sm-12" style="border: 2px solid white;word-wrap: break-word;border-radius: 15px;background-color:#202020;text-align:center;margin: 0px auto;">-->
<!--    {% if error_message %}-->
<!--        <h3 style="color:#8e2020;font-weight:bold;">{{ error_message }}</h3>-->
<!--    {% endif %}-->
    
<!--    <form role="form" action="{% url 'main:login'%}" method="post" enctype="multipart/form-data">-->
<!--      {% csrf_token %}-->
<!--    {% if request.GET.next %}-->
<!--        <input type="hidden" name="next" value="{{ request.GET.next }}">-->
<!--    {% endif %}-->
<!--      <div class="form-group">-->
<!--        <label for="id_username">Username:</label>-->
<!--        <input type="text" class="form-control" name="username" placeholder="Username">-->
<!--      </div>-->
      
<!--      <div class="form-group">-->
<!--        <label for="id_password">Password:</label>-->
<!--        <input type="password" class="form-control" name="password" placeholder="Password">-->
<!--      </div>-->
      
<!--      <button type="submit" class="btn btn-primary">Submit</button>-->
<!--    </form>-->
<!--    <br>-->

<!--</div>-->



{% endblock %}

main/templates/main/requestList.html
{% extends 'main/base.html' %}
{% block title %}Request List{% endblock %}

{% block body %}
{% load staticfiles %}
<div class="container-fluid" style="text-align: center;">
    <div class="row">
      <div class="col-sm-12">
        <h1>Request List</h1>
        <table class="table table-striped table-light" style="color:black;">
          <thead>
            <tr>
              <th scope="col">Title</th>
              <th scope="col">Description</th>
              <th scope="col">Technician</th>
              <!--<th scope="col">Handle</th>-->
            </tr>
          </thead>
          <tbody>
          {% for request in requestList %}
            <tr>
              <td scope="row">{{request.title}}</td>
              <td>{{request.description}}</td>
              <td>{{request.technician}}<br>{{request.technician.get_full_name}}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
        
          <h1></h1>
          <h1></h1>
          <h1></h1>
        
      </div>
    </div>
</div>
{% endblock %}

main/templates/main/technicianList.html
{% extends 'main/base.html' %}
{% block title %}Technician List{% endblock %}

{% block body %}
{% load staticfiles %}
<div class="container-fluid" style="text-align: center;">
    <div class="row">
      <div class="col-sm-12">
        <h1>Tech List</h1>
        
        <br>
        <table class="table table-striped table-light" style="color:black;">
          <thead>
            <tr>
              <th scope="col">Username</th>
              <th scope="col">Name</th>
              <th scope="col">Contact Info</th>
              
            </tr>
          </thead>
          <tbody>
          {% for t in technicianList %}
            <tr>
              <td>{{t.user_account.username}}</td>
              <td>{{t.get_full_name}}</td>
              <td>
                Email: <a href="mailto:{{t.email}}">{{t.email}}</a>
                <br>
                Phone: <a href="tel:{{t.phone_number}}">{{t.phone_number}}</a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
        
          <h1></h1>
          <h1></h1>
          <h1></h1>
        
      </div>
    </div>
</div>
{% endblock %}

main/templates/main/userInfo.html
{% extends 'main/base.html' %}
{% block title %}User Info{% endblock %}

{% block body %}
{% load staticfiles %}
<div class="container-fluid" style="text-align: center;">
    <div class="row">
      <div class="col-sm-12">
        <h1>username {{request.user}}</h1>
        <!--<h2><a href="/rl">Requests</a></h2>-->
      </div>
    </div>
</div>
{% endblock %}